version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sqlserver
    platform: linux/arm64
    environment:
      
      SA_PASSWORD: "reallyStrongPwd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend

  patienttrackingsystem:
    build:
      context: .
      dockerfile: PatientTrackingSystem/Dockerfile
    depends_on:
      - sqlserver
    platform: linux/arm64
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PatientTrackingSystemDb;User=sa;Password=YourStrongPassword!123;"
    ports:
      - "7275:7275"
    networks:
      - backend

networks:
  backend:
    driver: bridge